{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cpp11
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cpp11_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cpp11/cpp11_{{ version }}.tar.gz
  sha256: 0e8ac07f9d599b82e7a811f9d084e5125ae787b1ba04e5ba57f79e2642af091b

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('cpp11')"           # [not win]
    - "\"%R%\" -e \"library('cpp11')\""  # [win]

about:
  home: https://github.com/r-lib/cpp11
  license: MIT
  summary: Provides a header only, C++11 interface to R's C interface. Compared to other approaches 'cpp11' strives to be safe against long jumps from the C API as well as C++ exceptions, conform to normal R function semantics and supports interaction with 'ALTREP' vectors.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
